---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_IDENTIFIER:
  ALLOW_PAID_SERVICE_PLANS:
  APPLY_OPEN_SECURITY_GROUP:
  DATAFLOW_DB_PLAN:
  DATAFLOW_DB_SERVICE:
  DB_SERVICE_NAME:
  DB_SERVICE_PLAN:
  ORG:
  P_DATAFLOW_ENABLE_GLOBAL_ACCESS_TO_PLANS:
  SKIPPER_DB_PLAN:
  SKIPPER_DB_SERVICE:
  SPACE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-p-dataflow/task.sh
