---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_IDENTIFIER:
  DEPLOY_PCF_EVENT_ALERTS_INSTANCE_COUNT:
  MYSQL:
  MYSQL_EXTERNAL_DATABASE:
  MYSQL_EXTERNAL_HOST:
  MYSQL_EXTERNAL_PASSWORD:
  MYSQL_EXTERNAL_PORT:
  MYSQL_EXTERNAL_USERNAME:
  MYSQL_INTERNAL_PLAN_NAME:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-p-event-alerts/task.sh
