---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWD:
  CONCOURSE_URL:
  BUILD_PIPELINE_NAME:
  BUILD_TEAM_NAME:
  UPGRADE_PIPELINE_NAME:
  PRODUCT_NAME:
  PRODUCT_IDENTIFIER:
  PRODUCT_VERSION:
  PRODUCT_GLOB:

inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/set-upgrade-pipeline/task.sh
