---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_IDENTIFIER:
  REPLICATOR_NAME:
  ISOLATED_DIEGO_CELL_EXECUTOR_DISK_CAPACITY:
  ISOLATED_DIEGO_CELL_EXECUTOR_MEMORY_CAPACITY:
  ISOLATED_DIEGO_CELL_INSECURE_DOCKER_REGISTRY_LIST:
  ISOLATED_DIEGO_CELL_PLACEMENT_TAG:
  ISOLATED_HA_PROXY_INTERNAL_ONLY_DOMAINS:
  ISOLATED_HA_PROXY_STATIC_IPS:
  ISOLATED_HA_PROXY_TRUSTED_DOMAIN_CIDRS:
  ISOLATED_ROUTER_DISABLE_INSECURE_COOKIES:
  ISOLATED_ROUTER_DRAIN_WAIT:
  ISOLATED_ROUTER_ENABLE_WRITE_ACCESS_LOGS:
  ISOLATED_ROUTER_ENABLE_ZIPKIN:
  ISOLATED_ROUTER_EXTRA_HEADERS_TO_LOG:
  ISOLATED_ROUTER_LB_HEALTHY_THRESHOLD:
  ISOLATED_ROUTER_REQUEST_TIMEOUT_IN_SECONDS:
  ISOLATED_ROUTER_STATIC_IPS:
  ENABLE_GROOTFS:
  GARDEN_DISK_CLEANUP:
  GOROUTER_SSL_CIPHERS:
  HAPROXY_FORWARD_TLS:
  HAPROXY_FORWARD_TLS_ENABLE_BACKEND_CA:
  HAPROXY_MAX_BUFFER_SIZE:
  HAPROXY_SSL_CIPHERS:
  ISOLATION_SEGMENT_DOMAINS:
  NETWORKING_POE_SSL_NAME:
  NETWORKING_POE_SSL_CERT_PEM:
  NETWORKING_POE_SSL_CERT_PRIVATE_KEY_PEM:
  NFS_VOLUME_DRIVER:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVER_HOST:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVER_PORT:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVICE_ACCOUNT_PASSWORD:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_SERVICE_ACCOUNT_USER:
  NFS_VOLUME_DRIVER_ENABLE_LDAP_USER_FQDN:
  ROUTER_BACKEND_MAX_CONN:
  ROUTER_CLIENT_CERT_VALIDATION:
  ROUTER_ENABLE_PROXY:
  ROUTING_CUSTOM_CA_CERTIFICATES:
  ROUTING_DISABLE_HTTP:
  ROUTING_MINIMUM_TLS_VERSION:
  ROUTING_TABLE_SHARDING_MODE:
  ROUTING_TLS_TERMINATION:
  SKIP_CERT_VERIFY:
  SYSTEM_LOGGING:
  SYSTEM_LOGGING_ENABLED_HOST:
  SYSTEM_LOGGING_ENABLED_PORT:
  SYSTEM_LOGGING_ENABLED_PROTOCOL:
  SYSTEM_LOGGING_ENABLED_SYSLOG_RULE:
  SYSTEM_LOGGING_ENABLED_TLS_CA_CERT:
  SYSTEM_LOGGING_ENABLED_TLS_ENABLED:
  SYSTEM_LOGGING_ENABLED_TLS_PERMITTED_PEER:
  SYSTEM_LOGGING_ENABLED_USE_TCP_FOR_FILE_FORWARDING_LOCAL_TRANSPORT:
  ISOLATED_HA_PROXY_INSTANCES:
  ISOLATED_HA_PROXY_INSTANCE_TYPE:
  ISOLATED_ROUTER_INSTANCES:
  ISOLATED_ROUTER_INSTANCE_TYPE:
  ISOLATED_DIEGO_CELL_INSTANCES:
  ISOLATED_DIEGO_CELL_INSTANCE_TYPE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-is-tile/task.sh
