resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pipelines-repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: rabbitmq-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((rmq_product_name))
    product_version: ((rmq_product_version))

- name: mysql-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((mysql_product_name))
    product_version: ((mysql_product_version))

- name: spring-cloud-services-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((scs_product_name))
    product_version: ((scs_product_version))

- name: redis-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((redis_product_name))
    product_version: ((redis_product_version))

- name: jmx-bridge-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((jmx_bridge_product_name))
    product_version: ((jmx_bridge_product_version))

- name: pcf-metrics-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((pcf_metrics_product_name))
    product_version: ((pcf_metrics_product_version))

- name: time-schedule
  type: time
  source: {interval: 24h}

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: ((git_token))

jobs:
- name: scheduler
  plan:
  - get: time-schedule
    trigger: true
  - get: rabbitmq-product
    params:
      globs: []
  - get: mysql-product
    params:
      globs: []
  - get: spring-cloud-services-product
    params:
      globs: []
  - get: redis-product
    params:
      globs: []
  - get: jmx-bridge-product
    params:
      globs: []
  - get: pcf-metrics-product
    params:
      globs: []

- name: upload-product-rabbitmq
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: rabbitmq-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
      passed: [scheduler]
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-for-rabbitmq
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product-rabbitmq]
    - get: pivnet-product
      resource: rabbitmq-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-product-rabbitmq]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product-rabbitmq]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-product-rabbitmq]
    - get: jq
      params:
        globs:
        - "*linux64*"

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: stage-product-rabbitmq
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-for-rabbitmq]
    - get: pivnet-product
      resource: rabbitmq-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-stemcell-for-rabbitmq]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-stemcell-for-rabbitmq]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((rmq_product_identifier))

- name: upload-product-mysql
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: mysql-product
      params:
        globs:
        - "*.pivotal"
      passed: [scheduler]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-for-mysql
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product-mysql]
    - get: pivnet-product
      resource: mysql-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
      passed: [upload-product-mysql]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product-mysql]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-product-mysql]
  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: stage-product-mysql
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-for-mysql]
    - get: pivnet-product
      resource: mysql-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-stemcell-for-mysql]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-stemcell-for-mysql]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((mysql_product_identifier))

- name: upload-product-spring-cloud-services
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: spring-cloud-services-product
      params:
        globs:
        - "*.pivotal"
      passed: [scheduler]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-for-spring-cloud-services
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product-spring-cloud-services]
    - get: pivnet-product
      resource: spring-cloud-services-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
      passed: [upload-product-spring-cloud-services]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product-spring-cloud-services]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-product-spring-cloud-services]

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: stage-product-spring-cloud-services
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-for-spring-cloud-services]
    - get: pivnet-product
      resource: spring-cloud-services-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-stemcell-for-spring-cloud-services]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-stemcell-for-spring-cloud-services]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((scs_product_identifier))

- name: upload-product-redis
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: redis-product
      params:
        globs:
        - "*.pivotal"
      passed: [scheduler]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-for-redis
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product-redis]
    - get: pivnet-product
      resource: redis-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
      passed: [upload-product-redis]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product-redis]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-product-redis]

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: stage-product-redis
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-for-redis]
    - get: pivnet-product
      resource: redis-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-stemcell-for-redis]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-stemcell-for-redis]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((redis_product_identifier))

- name: upload-product-jmx-bridge
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: jmx-bridge-product
      params:
        globs:
        - "*.pivotal"
      passed: [scheduler]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-for-jmx-bridge
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product-jmx-bridge]
    - get: pivnet-product
      resource: jmx-bridge-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
      passed: [upload-product-jmx-bridge]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product-jmx-bridge]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-product-jmx-bridge]

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: stage-product-jmx-bridge
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-for-jmx-bridge]
    - get: pivnet-product
      resource: jmx-bridge-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-stemcell-for-jmx-bridge]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-stemcell-for-jmx-bridge]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((jmx_bridge_product_identifier))

- name: upload-product-pcf-metrics
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: pcf-metrics-product
      params:
        globs:
        - "*.pivotal"
      passed: [scheduler]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-for-pcf-metrics
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-product-pcf-metrics]
    - get: pivnet-product
      resource: pcf-metrics-product
      params:
        globs:
        - "*.pivotal"
      trigger: true
      passed: [upload-product-pcf-metrics]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-product-pcf-metrics]
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-product-pcf-metrics]

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: stage-product-pcf-metrics
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-for-pcf-metrics]
    - get: pivnet-product
      resource: pcf-metrics-product
      params:
        globs:
        - "*.pivotal"
      passed: [upload-stemcell-for-pcf-metrics]
      trigger: true
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [upload-stemcell-for-pcf-metrics]

  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: ((pcf_metrics_product_identifier))

- name: apply-changes
  plan:
  - aggregate:
    - get: pipelines-repo
      trigger: true
      passed: [stage-product-spring-cloud-services, stage-product-redis, stage-product-jmx-bridge, stage-product-mysql, stage-product-rabbitmq, stage-product-pcf-metrics]
    - get: om-cli
      params:
        globs:
        - "*-linux"
      passed: [stage-product-spring-cloud-services, stage-product-redis, stage-product-jmx-bridge, stage-product-mysql, stage-product-rabbitmq, stage-product-pcf-metrics]

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
