---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_IDENTIFIER:
  ALLOW_LOWER_CASE_TABLE_NAMES_VIA_CONFIG_PARAM:
  AUDIT_LOGGING_ENABLED:
  BACKUPS_SELECTOR:
  BACKUPS_SELECTOR_AZURE_ACCOUNT:
  BACKUPS_SELECTOR_AZURE_BLOB_STORE_BASE_URL:
  BACKUPS_SELECTOR_AZURE_CONTAINER:
  BACKUPS_SELECTOR_AZURE_CRON_SCHEDULE:
  BACKUPS_SELECTOR_AZURE_ENABLE_EMAIL_ALERTS:
  BACKUPS_SELECTOR_AZURE_PATH:
  BACKUPS_SELECTOR_AZURE_STORAGE_ACCESS_KEY:
  BACKUPS_SELECTOR_GCS_BUCKET_NAME:
  BACKUPS_SELECTOR_GCS_CRON_SCHEDULE:
  BACKUPS_SELECTOR_GCS_ENABLE_EMAIL_ALERTS:
  BACKUPS_SELECTOR_GCS_PROJECT_ID:
  BACKUPS_SELECTOR_GCS_SERVICE_ACCOUNT_JSON:
  BACKUPS_SELECTOR_S3_ACCESS_KEY_ID:
  BACKUPS_SELECTOR_S3_BUCKET_NAME:
  BACKUPS_SELECTOR_S3_CRON_SCHEDULE:
  BACKUPS_SELECTOR_S3_ENABLE_EMAIL_ALERTS:
  BACKUPS_SELECTOR_S3_ENDPOINT_URL:
  BACKUPS_SELECTOR_S3_PATH:
  BACKUPS_SELECTOR_S3_REGION:
  BACKUPS_SELECTOR_S3_SECRET_ACCESS_KEY:
  BACKUPS_SELECTOR_SCP_CRON_SCHEDULE:
  BACKUPS_SELECTOR_SCP_DESTINATION:
  BACKUPS_SELECTOR_SCP_ENABLE_EMAIL_ALERTS:
  BACKUPS_SELECTOR_SCP_FINGERPRINT:
  BACKUPS_SELECTOR_SCP_KEY:
  BACKUPS_SELECTOR_SCP_PORT:
  BACKUPS_SELECTOR_SCP_SERVER:
  BACKUPS_SELECTOR_SCP_USER:
  ENABLE_LOWER_CASE_TABLE_NAMES:
  ENABLE_READ_ONLY_ADMIN:
  GLOBAL_SERVICE_INSTANCE_LIMIT:
  LOCAL_INFILE:
  MYSQL_METRICS_FREQUENCY:
  PLAN1_SELECTOR:
  PLAN1_SELECTOR_ACTIVE_ACCESS_DROPDOWN:
  PLAN1_SELECTOR_ACTIVE_AZ_MULTI_SELECT:
  PLAN1_SELECTOR_ACTIVE_DESCRIPTION:
  PLAN1_SELECTOR_ACTIVE_DISK_SIZE:
  PLAN1_SELECTOR_ACTIVE_INSTANCE_LIMIT:
  PLAN1_SELECTOR_ACTIVE_MULTI_NODE_DEPLOYMENT:
  PLAN1_SELECTOR_ACTIVE_NAME:
  PLAN1_SELECTOR_ACTIVE_VM_TYPE:
  PLAN2_SELECTOR:
  PLAN2_SELECTOR_ACTIVE_ACCESS_DROPDOWN:
  PLAN2_SELECTOR_ACTIVE_AZ_MULTI_SELECT:
  PLAN2_SELECTOR_ACTIVE_DESCRIPTION:
  PLAN2_SELECTOR_ACTIVE_DISK_SIZE:
  PLAN2_SELECTOR_ACTIVE_INSTANCE_LIMIT:
  PLAN2_SELECTOR_ACTIVE_MULTI_NODE_DEPLOYMENT:
  PLAN2_SELECTOR_ACTIVE_NAME:
  PLAN2_SELECTOR_ACTIVE_VM_TYPE:
  PLAN3_SELECTOR:
  PLAN3_SELECTOR_ACTIVE_ACCESS_DROPDOWN:
  PLAN3_SELECTOR_ACTIVE_AZ_MULTI_SELECT:
  PLAN3_SELECTOR_ACTIVE_DESCRIPTION:
  PLAN3_SELECTOR_ACTIVE_DISK_SIZE:
  PLAN3_SELECTOR_ACTIVE_INSTANCE_LIMIT:
  PLAN3_SELECTOR_ACTIVE_MULTI_NODE_DEPLOYMENT:
  PLAN3_SELECTOR_ACTIVE_NAME:
  PLAN3_SELECTOR_ACTIVE_VM_TYPE:
  PLAN4_SELECTOR:
  PLAN4_SELECTOR_ACTIVE_ACCESS_DROPDOWN:
  PLAN4_SELECTOR_ACTIVE_AZ_MULTI_SELECT:
  PLAN4_SELECTOR_ACTIVE_DESCRIPTION:
  PLAN4_SELECTOR_ACTIVE_DISK_SIZE:
  PLAN4_SELECTOR_ACTIVE_INSTANCE_LIMIT:
  PLAN4_SELECTOR_ACTIVE_MULTI_NODE_DEPLOYMENT:
  PLAN4_SELECTOR_ACTIVE_NAME:
  PLAN4_SELECTOR_ACTIVE_VM_TYPE:
  PLAN5_SELECTOR:
  PLAN5_SELECTOR_ACTIVE_ACCESS_DROPDOWN:
  PLAN5_SELECTOR_ACTIVE_AZ_MULTI_SELECT:
  PLAN5_SELECTOR_ACTIVE_DESCRIPTION:
  PLAN5_SELECTOR_ACTIVE_DISK_SIZE:
  PLAN5_SELECTOR_ACTIVE_INSTANCE_LIMIT:
  PLAN5_SELECTOR_ACTIVE_MULTI_NODE_DEPLOYMENT:
  PLAN5_SELECTOR_ACTIVE_NAME:
  PLAN5_SELECTOR_ACTIVE_VM_TYPE:
  SYSLOG_MIGRATION_SELECTOR:
  SYSLOG_MIGRATION_SELECTOR_ENABLED_ADDRESS:
  SYSLOG_MIGRATION_SELECTOR_ENABLED_CA_CERT:
  SYSLOG_MIGRATION_SELECTOR_ENABLED_PERMITTED_PEER:
  SYSLOG_MIGRATION_SELECTOR_ENABLED_PORT:
  SYSLOG_MIGRATION_SELECTOR_ENABLED_TLS_ENABLED:
  SYSLOG_MIGRATION_SELECTOR_ENABLED_TRANSPORT_PROTOCOL:
  USERSTAT:
  VM_EXTENSIONS:
  DEDICATED_MYSQL_BROKER_INSTANCES:
  DEDICATED_MYSQL_BROKER_INSTANCE_TYPE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-mysql-v2/task.sh
