---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_IDENTIFIER:
  ALLOW_PAID_SERVICE_PLANS:
  APPLY_OPEN_SECURITY_GROUP:
  HTTP_PROXY:
  NEWRELIC_INSIGHTS_BASE_URL:
  NEWRELIC_INSIGHTS_INSERT_KEY:
  NEWRELIC_INSIGHTS_RPM_ID:
  NO_PROXY:
  NOZZLE_ADMIN_PASSWORD:
  NOZZLE_ADMIN_USER:
  NOZZLE_APP_DETAIL_INTERVAL:
  NOZZLE_EXCLUDED_DEPLOYMENTS:
  NOZZLE_EXCLUDED_JOBS:
  NOZZLE_EXCLUDED_ORIGINS:
  NOZZLE_FIREHOSE_SUBSCRIPTION_ID:
  NOZZLE_INSTANCES:
  NOZZLE_PASSWORD:
  NOZZLE_SELECTED_EVENTS:
  NOZZLE_SKIP_SSL:
  NOZZLE_TRAFFIC_CONTROLLER_URL:
  NOZZLE_UAA_URL:
  NOZZLE_USERNAME:
  ORG:
  SPACE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-nr-firehose-nozzle/task.sh
