---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_IDENTIFIER:
  ALLOW_PAID_SERVICE_PLANS:
  APP_URI:
  APPD_PLANS:
  APPDYNAMICS_SERVICE_BROKER_ENABLE_GLOBAL_ACCESS_TO_PLANS:
  APPLY_OPEN_SECURITY_GROUP:
  ORG:
  SPACE:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-appdynamics/task.sh
