---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PRODUCT_IDENTIFIER:
  PRODUCT_PROPERTIES:
  PRODUCT_RESOURCES:
  PRODUCT_NETWORK_AZS:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-product/task.sh
