---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  GOVC_HOST:
  OPS_MANAGER_SETTINGS:

inputs:
  - name: pivnet-product
  - name: pipelines-repo
  - name: govc
  - name: jq

run:
  path: pipelines-repo/tasks/import-opsman/task.sh
